/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simulasyon;

import cihaz.Cihaz;
import cihaz.Anahtar;
import cihaz.Kablo;
import javax.swing.*;
import javax.swing.UIManager.*;
import java.awt.*;
import java.awt.event.MouseEvent;
/**
 *
 * @author Suayb Simsek
 */
public class AnaFrame extends JFrame {

    /**
     * Creates new form AnaFrame
     */
    public static EnumMod mod;
    public static EnumCihaz cihazlar;
    public static MouseEvent pressed, dragged, click, released, mouseMove;
    public Devre ckt;
    public Cihaz pressedCihaz, releasedCihaz;
    public Kablo pressedKablo, releasedKablo;
    public int giris_sayisi;
    private Cihaz secili_cihaz;
    
    public AnaFrame() {
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.kablo;
        ckt = new Devre();
        giris_sayisi = 2;
        
        try {
            giris_sayisi = 1/0;
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                SwingUtilities.updateComponentTreeUI(this);
            }
            catch(Exception ee)  {
                ee.printStackTrace();
            }
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AracPanel = new javax.swing.JPanel();
        andButton = new javax.swing.JButton();
        orButton = new javax.swing.JButton();
        notButton = new javax.swing.JButton();
        anahtarButton = new javax.swing.JButton();
        ledButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        and3Button1 = new javax.swing.JButton();
        or3Button1 = new javax.swing.JButton();
        durumLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DevrePanel = new simulasyon.DevrePanel(ckt);
        toolPanel = new javax.swing.JPanel();
        calistirButton = new javax.swing.JButton();
        temizleButton = new javax.swing.JButton();
        durdurButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sayisal Elektronik Simulasyonu");
        setBackground(java.awt.Color.black);
        setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        setMinimumSize(new java.awt.Dimension(700, 600));
        setName("mainFrame"); // NOI18N

        AracPanel.setBackground(java.awt.Color.black);
        AracPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AracPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        andButton.setBackground(java.awt.Color.black);
        andButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\and.png")); // NOI18N
        andButton.setToolTipText("");
        andButton.setContentAreaFilled(false);
        andButton.setHideActionText(true);
        andButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        andButton.setIconTextGap(15);
        andButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                andButtonMouseDragged(evt);
            }
        });

        orButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\or.png")); // NOI18N
        orButton.setContentAreaFilled(false);
        orButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                orButtonMouseDragged(evt);
            }
        });

        notButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\not.png")); // NOI18N
        notButton.setContentAreaFilled(false);
        notButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                notButtonMouseDragged(evt);
            }
        });

        anahtarButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\switch.png")); // NOI18N
        anahtarButton.setToolTipText("");
        anahtarButton.setContentAreaFilled(false);
        anahtarButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                anahtarButtonMouseDragged(evt);
            }
        });

        ledButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\lamp.png")); // NOI18N
        ledButton.setToolTipText("");
        ledButton.setContentAreaFilled(false);
        ledButton.setFocusable(false);
        ledButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ledButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ledButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ledButtonMouseDragged(evt);
            }
        });

        and3Button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\and3.png")); // NOI18N
        and3Button1.setContentAreaFilled(false);
        and3Button1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                and3Button1MouseDragged(evt);
            }
        });

        or3Button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\or3.png")); // NOI18N
        or3Button1.setContentAreaFilled(false);
        or3Button1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                or3Button1MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout AracPanelLayout = new javax.swing.GroupLayout(AracPanel);
        AracPanel.setLayout(AracPanelLayout);
        AracPanelLayout.setHorizontalGroup(
            AracPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AracPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AracPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AracPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AracPanelLayout.createSequentialGroup()
                        .addComponent(andButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(AracPanelLayout.createSequentialGroup()
                        .addComponent(notButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AracPanelLayout.createSequentialGroup()
                        .addGroup(AracPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(and3Button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(or3Button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AracPanelLayout.createSequentialGroup()
                        .addGroup(AracPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ledButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anahtarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        AracPanelLayout.setVerticalGroup(
            AracPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AracPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(andButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(and3Button1)
                .addGap(47, 47, 47)
                .addComponent(orButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(or3Button1)
                .addGap(65, 65, 65)
                .addComponent(notButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(anahtarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(ledButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        AracPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {and3Button1, andButton, notButton, or3Button1, orButton});

        durumLabel.setBackground(java.awt.Color.black);
        durumLabel.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        durumLabel.setForeground(java.awt.Color.white);
        durumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        durumLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        durumLabel.setOpaque(true);

        jScrollPane3.setBackground(java.awt.Color.black);
        jScrollPane3.setBorder(null);
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(1920, 1080));

        DevrePanel.setBackground(new java.awt.Color(253, 254, 238));
        DevrePanel.setToolTipText("");
        DevrePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DevrePanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        DevrePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                devrePanelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                devrePanelMouseMoved(evt);
            }
        });
        DevrePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devrePanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                devrePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                devrePanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout DevrePanelLayout = new javax.swing.GroupLayout(DevrePanel);
        DevrePanel.setLayout(DevrePanelLayout);
        DevrePanelLayout.setHorizontalGroup(
            DevrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        DevrePanelLayout.setVerticalGroup(
            DevrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(DevrePanel);

        toolPanel.setBackground(java.awt.Color.black);

        calistirButton.setBackground(java.awt.Color.black);
        calistirButton.setFont(new java.awt.Font("Courier New", 1, 32)); // NOI18N
        calistirButton.setForeground(java.awt.Color.white);
        calistirButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\play-button.png")); // NOI18N
        calistirButton.setText("Calistir");
        calistirButton.setToolTipText("Simulasyon");
        calistirButton.setContentAreaFilled(false);
        calistirButton.setFocusable(false);
        calistirButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calistirButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        calistirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calistirButtonActionPerformed(evt);
            }
        });

        temizleButton.setBackground(java.awt.Color.black);
        temizleButton.setFont(new java.awt.Font("Courier New", 1, 32)); // NOI18N
        temizleButton.setForeground(java.awt.Color.white);
        temizleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\garbage.png")); // NOI18N
        temizleButton.setText("Temizle");
        temizleButton.setToolTipText("Temizle");
        temizleButton.setContentAreaFilled(false);
        temizleButton.setFocusable(false);
        temizleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        temizleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        temizleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleButtonActionPerformed(evt);
            }
        });

        durdurButton.setBackground(java.awt.Color.black);
        durdurButton.setFont(new java.awt.Font("Courier New", 1, 32)); // NOI18N
        durdurButton.setForeground(java.awt.Color.white);
        durdurButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Şuayb Şimşek\\Documents\\NetBeansProjects\\Muh_Proje\\Image\\hold.png")); // NOI18N
        durdurButton.setText("Durdur");
        durdurButton.setToolTipText("Simulasyon");
        durdurButton.setContentAreaFilled(false);
        durdurButton.setFocusable(false);
        durdurButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        durdurButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        durdurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durdurButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolPanelLayout = new javax.swing.GroupLayout(toolPanel);
        toolPanel.setLayout(toolPanelLayout);
        toolPanelLayout.setHorizontalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(temizleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271)
                .addComponent(calistirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(durdurButton)
                .addGap(65, 65, 65))
        );

        toolPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {calistirButton, durdurButton, temizleButton});

        toolPanelLayout.setVerticalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durdurButton)
                    .addComponent(calistirButton)
                    .addComponent(temizleButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        toolPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {calistirButton, durdurButton, temizleButton});

        jMenuBar1.setBackground(java.awt.Color.black);
        jMenuBar1.setBorder(null);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AracPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE))
            .addComponent(durumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(AracPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(durumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void devrePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devrePanelMouseMoved

        mouseMove = evt;
        if ( mod == EnumMod.cizim ) {
            if ( cihazlar != EnumCihaz.kablo )    {
                ckt.setGecici(mouseMove, giris_sayisi);
            }
            else    {
                Kordinat c = new Kordinat(evt);
                Cihaz temp = ckt.searchCihaz(c);

               
                if ( temp != null ) {
                    int indx = temp.isOnGirisLeg(c);
                    if ( indx > -1 )    ckt.noktaFlag = true;
                    else if ( temp.isOnCikisLeg(c) )  {
                        ckt.noktaFlag = true;
                    }
                    else    ckt.noktaFlag = false;
                }
                else    ckt.noktaFlag = false;
            }
        }
        else if ( mod == EnumMod.Calistir )    {
            Kordinat c = new Kordinat(evt);
            Cihaz temp = ckt.searchKaynak(c);
            if ( temp != null ) {
                DevrePanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
            else    {
                DevrePanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        }
        DevrePanel.repaint();
        
    }//GEN-LAST:event_devrePanelMouseMoved

    private void devrePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devrePanelMouseDragged
        // TODO add your handling code here:
        dragged = evt;
        ckt.bitis = new Kordinat(dragged);
        DevrePanel.repaint();
    }//GEN-LAST:event_devrePanelMouseDragged

    private void devrePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devrePanelMousePressed
        // TODO add your handling code here:
        if ( mod == EnumMod.cizim )  {
            if ( cihazlar == EnumCihaz.kablo )    {
                Cihaz d = ckt.searchCihaz(new Kordinat(evt));
                if ( d != null )    {
                    int indx = d.isOnGirisLeg(new Kordinat(evt));
                    if ( indx > -1 || d.isOnCikisLeg(new Kordinat(evt)))    {
                        pressed = evt;
                        pressedCihaz = d;
                        ckt.baslangic = new Kordinat(pressed);
                    }
                    else {
                        pressed = null;
                        pressedCihaz = null;
                        pressedKablo = null;
                    }
                }
                else    {
                    Kablo w = ckt.searchKablo(new Kordinat(evt));
                    if ( w != null )    {
                        pressed = evt;
                        pressedKablo = w;
                        ckt.baslangic = new Kordinat(pressed);
                    }
                    else {
                        pressed = null;
                        ckt.baslangic = null;
                        pressedKablo = null;
                    }
                }
            }
        }
    }//GEN-LAST:event_devrePanelMousePressed

    private void devrePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devrePanelMouseClicked
        // TODO add your handling code here:
        if ( mod == EnumMod.cizim ) {
            ckt.placeGecici();
            cihazlar = EnumCihaz.kablo;
            durumLabel.setText("Baglanti Modu");
        }
        else if ( mod == EnumMod.Calistir )    {
            Anahtar s = ckt.searchKaynak(new Kordinat(evt));
            if ( s != null )    s.toggleCikis();
        }
        else if ( mod == EnumMod.Secme ) {
            if ( secili_cihaz != null )   {
                secili_cihaz.setSelected(false);
                secili_cihaz = null;
            }
            Kordinat cd = new Kordinat(evt);
            Cihaz d = ckt.searchCihaz(cd);
            if ( d == null )    d = ckt.searchKaynak(cd);
            if ( d == null )    return;
            d.setSelected(true);
            secili_cihaz = d;
           
        }
        DevrePanel.repaint();
    }//GEN-LAST:event_devrePanelMouseClicked

    private void devrePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devrePanelMouseReleased
        // TODO add your handling code here:
        dragged = null;
        ckt.bitis = null;
        if ( mod == EnumMod.cizim )  {
            if ( cihazlar == EnumCihaz.kablo )    {
                Cihaz d = ckt.searchCihaz(new Kordinat(evt));
                if ( d != null )    {
                    int indx = d.isOnGirisLeg(new Kordinat(evt));
                    if ( indx > -1 || d.isOnCikisLeg(new Kordinat(evt)))    {
                        released = evt;
                        releasedCihaz = d;
                        ckt.addKablo(new Kordinat(pressed), pressedCihaz, new Kordinat(released), releasedCihaz);
                    }
                    else {
                        released = null;
                        releasedCihaz = null;
                    }
                }
                else    {
                    Kablo w = ckt.searchKablo(new Kordinat(evt));
                    if ( w != null )    {
                        pressed = evt;
                        pressedKablo = w;
                    }
                    else {
                        pressed = null;
                        pressedKablo = null;
                    }
                }
            }
        }
        DevrePanel.repaint();
    }//GEN-LAST:event_devrePanelMouseReleased

    private void or3Button1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_or3Button1MouseDragged
        if ( mod == EnumMod.Calistir ) {
            durumLabel.setText("Cizim moduna gecmek icin Durdur Butonuna Tikla");
            return;
        }
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.or;
        durumLabel.setText("Or Kapisi");
        giris_sayisi = 3;
    }//GEN-LAST:event_or3Button1MouseDragged

    private void and3Button1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_and3Button1MouseDragged
        if ( mod == EnumMod.Calistir ) {
            durumLabel.setText("Cizim moduna gecmek icin Durdur Butonuna Tikla");
            return;
        }
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.and;
        durumLabel.setText("And Kapisi");
        giris_sayisi = 3;
    }//GEN-LAST:event_and3Button1MouseDragged

    private void ledButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ledButtonMouseDragged
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.led;
        giris_sayisi = 1;
        durumLabel.setText("LED");
    }//GEN-LAST:event_ledButtonMouseDragged

    private void anahtarButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anahtarButtonMouseDragged
        durumLabel.setText("Giris Kontrol");
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.anahtar;
    }//GEN-LAST:event_anahtarButtonMouseDragged

    private void notButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notButtonMouseDragged
        if ( mod == EnumMod.Calistir ) {
            durumLabel.setText("Cizim moduna gecmek icin Durdur Butonuna Tikla");
            return;
        }
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.not;
        durumLabel.setText("Not Kapisi");
        giris_sayisi = 1;
    }//GEN-LAST:event_notButtonMouseDragged

    private void orButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orButtonMouseDragged
        if ( mod == EnumMod.Calistir ) {
            durumLabel.setText("Cizim moduna gecmek icin Durdur Butonuna Tikla");
            return;
        }
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.or;
        durumLabel.setText("Or Kapisi");
        giris_sayisi = 2;
    }//GEN-LAST:event_orButtonMouseDragged

    private void andButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_andButtonMouseDragged
        if ( mod == EnumMod.Calistir ) {
            durumLabel.setText("Cizim moduna gecmek icin Durdur Butonuna Tikla");
            return;
        }
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.and;
        durumLabel.setText("And Kapisi");
        giris_sayisi = 2;

    }//GEN-LAST:event_andButtonMouseDragged

    private void durdurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durdurButtonActionPerformed
        // TODO add your handling code here:
        mod = EnumMod.cizim;
        cihazlar = EnumCihaz.kablo;
        durumLabel.setText("Cizim Modu");
        int l = ckt.anahtar.size();
        DevrePanel.repaint();
    }//GEN-LAST:event_durdurButtonActionPerformed

    private void calistirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calistirButtonActionPerformed
        // TODO add your handling code here:
        if ( !ckt.gecerliMi() )   {
            JOptionPane.showMessageDialog(null, "Tamamlanmamis Devre");
            return;
        }
        if ( mod == EnumMod.Calistir ) return;
        mod = EnumMod.Calistir;
        durumLabel.setText("Devre Simulasyonu");
        int l = ckt.anahtar.size();
        for ( int i = 0; i < l; i++ )   {
            Anahtar s = ckt.anahtar.get(i);
            s.setCikis(false);
        }
        DevrePanel.repaint();
    }//GEN-LAST:event_calistirButtonActionPerformed

    private void temizleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleButtonActionPerformed
        // TODO add your handling code here:
        ckt.clear();
        DevrePanel.repaint();
    }//GEN-LAST:event_temizleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AracPanel;
    private javax.swing.JPanel DevrePanel;
    private javax.swing.JButton anahtarButton;
    private javax.swing.JButton and3Button1;
    private javax.swing.JButton andButton;
    private javax.swing.JButton calistirButton;
    private javax.swing.JButton durdurButton;
    private javax.swing.JLabel durumLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton ledButton;
    private javax.swing.JButton notButton;
    private javax.swing.JButton or3Button1;
    private javax.swing.JButton orButton;
    private javax.swing.JButton temizleButton;
    private javax.swing.JPanel toolPanel;
    // End of variables declaration//GEN-END:variables
}
